### ISSUE TITLE
very very nice and funny - cheater

### ISSUE THREAD

**Issue by r00ta** [MrMugiwara/WriteupsCTF#1]
Very very nice write up: it's funny that your parameters in gimp are equal to the mine one in my write up (https://github.com/r00ta/myWriteUps/blob/master/GoogleCTF/for1/README.md). Is it just a coincidence?

**Comment by pagabuc** [comment]
And also, what about the "Mer" in the top left corner of your screenshot? Doesn't it means that you solved the challenge "Mercredi" aka TODAY?

**Comment by r00ta** [comment]
On CTF Time https://ctftime.org/event/303 you got only 75 points: this challenge was 100 points. You didn't solved this challenge: you just copied my write up https://github.com/r00ta/myWriteUps/blob/master/GoogleCTF/for1/README.md . Please remove it and be fair in the future
